---
title: "R Notebook"
output: 
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)
library(xml2)
library(rvest)
```

```{r}
files <- paste0(here::here(),"/",list.files("Data.nosync",
                                        pattern = "*?\\.csv",
                                        full.names = TRUE)) %>% 
          as.list()

files %>% 
map(~read.csv(.x, nrows = 100))
```

```{r}
foo <- read_csv("Data.nosync/case_file.csv") %>% 


foo
  
```

```{r}
Cleaned_df <- read_csv("Data.nosync/Trademarks_only.csv") %>% 
  filter(str_detect(statement_text,"\"*\""))  %>%
  mutate(wordmark = str_extract(statement_text, "\"(.*?)\""),
         clean_wordmark = str_remove_all(wordmark, "\"|\\.|,"),
         wordmark_only = str_remove_all(clean_wordmark,"[[:punct:]]") %>%
           str_to_lower()
         ) %>%
  filter(str_length(clean_wordmark) > 2)

Cleaned_df
```


```{r}
TM_clean <- Cleaned_df %>%
  select(wordmark = clean_wordmark, serial_no)


# write_csv(TM_clean, "Data.nosync/TM_clean.csv")

```

```{r}
Courtcase_TM <- read_xml("Data.nosync/USPTO_TTAB_decisions.xml") %>% 
  xml_find_all("//mark-text") %>% 
  xml_text() %>% 
  trimws() %>%
  as_tibble() %>% 
  distinct() %>% 
  mutate(wordmark = str_replace_all(value, "[[:punct:]]", ""),
                 wordmark = str_to_lower(wordmark))

Courtcase_TM

# Courtcase_TM  %>% 
#   write_csv("Data.nosync/wordmark_cases.csv")
```


## Extracting Court Case XML
```{r}
TM_XML <- "Data.nosync/USPTO_TTAB_decisions.xml"

TM_XML <- read_xml(TM_XML)

Court_case_TM <- TM_XML %>% 
  xml_find_all('//property') %>% 
    map_dfr(~flatten(c(xml_attrs(.x), 
                       map(xml_children(.x), 
                           ~set_names(as.list(xml_text(.x)), xml_name(.x)))))) %>%
    type_convert()

Court_case_TM 
```


```{r}
data <- "Data.nosync/USPTO_TTAB_decisions.xml"

Proceeding_Court_case_TM <- TM_XML  %>% 
  xml_find_all('//proceeding-entry') %>% 
    map_dfr(~flatten(c(xml_attrs(.x), 
                       map(xml_children(.x), 
                           ~set_names(as.list(xml_text(.x)), xml_name(.x)))))) %>%
    type_convert()

Proceeding_Court_case_TM 
```


## Cleaning wordmarks
```{r}
TMs <- read_csv("Data.nosync/Courtcase_TM.csv")

Wordmark_court_clean <- TMs %>% 
  janitor::clean_names() %>% 
  filter(!is.na(mark_text)) %>% 
  mutate(mark_text = str_remove_all(mark_text, "[[:punct:]]"),
         mark_text = str_to_lower(mark_text))

Wordmark_court_clean
```


```{r}
combined_courtcase_TM <- Proceeding_Court_case_TM %>%
  janitor::clean_names() %>%
  filter(!is.na(party_information)) %>%
  mutate(identifier = str_extract(party_information, "^[^\\d]*(\\d+)") %>% as.numeric()) %>% 
  inner_join(Wordmark_court_clean, by = "identifier")

combined_courtcase_TM 
```

## Court case info
```{r}
TM_casefiles <- read_csv("Data.nosync/combined_courtcase_TM.csv") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(mark_text))

TM_casefiles %>% 
  count(type_code)
```

```{r}
TM_cancelled_courtcases <- TM_casefiles %>% 
  filter(type_code %in% c("CAN")) %>% 
  select(number, type_code, filing_date,identifier, serial_number, registration_number,
         mark_text) %>% 
  mutate(mark_text = str_to_lower(mark_text)) %>% 
  group_by(number) %>% 
  summarize(count = n())

TM_cancelled_courtcases
```

## Opposition cases
```{r}
TM_opposition_courtcases <- TM_casefiles %>% 
  filter(type_code == "OPP") %>% 
  select(number, type_code, filing_date,identifier, serial_number, registration_number,
         mark_text) %>% 
  mutate(mark_text = str_to_lower(mark_text)) %>% 
  distinct(mark_text,.keep_all = TRUE)

TM_opposition_courtcases
```
```{r}
TM_extension_courtcases <- TM_casefiles %>% 
  filter(type_code %in% c("EXT")) %>% 
  select(number, type_code, filing_date,identifier, serial_number, registration_number,
         mark_text) %>% 
  mutate(mark_text = str_to_lower(mark_text)) %>% 
  distinct(mark_text,.keep_all = TRUE)

TM_extension_courtcases
```
```{r}
```



```{r}
read_csv("Data.nosync/TM_clean_soundex.csv") %>% 
  filter(str_detect(wordmark, "frickin"))
```

